### ISSUE TITLE
Editing Custom Bangs Creates New Ones

### ISSUE THREAD

**Issue by frozolotl** [WhistlingZephyr/banger#1]
After pressing "Edit" on a custom bang and changing the shortcut, the old shortcut does not get removed and a new one appears with the new shortcut.

I expect the old bang to disappear after editing and saving one.

![before](https://user-images.githubusercontent.com/44589151/213131010-99e8d990-5e13-46dd-b7ed-a18fe3d0cb81.png)
![after](https://user-images.githubusercontent.com/44589151/213131208-9464936f-09eb-4521-950a-a3f1ed01b2ca.png)
![list of bangs](https://user-images.githubusercontent.com/44589151/213131506-31e0ef59-f72d-4663-ae17-3bc1c79d2876.png)

**Comment by WhistlingZephyr** [comment]
Hello! Thanks a lot for reporting the issue.

Unfortunately Mozilla took around a whole week to approve newer versions, but it's been fixed in v0.2.30! And I've removed the custom content security policy so future reviews should be a lot quicker.

Thanks again!

(The commit that it was fixed in: https://github.com/WhistlingZephyr/banger/commit/da09351f5806b8dcff6903560a707e593d545f9a)
