### ISSUE TITLE
Feature: Option to disable case sensitivity

### ISSUE THREAD

**Issue by TorMechia** [WhistlingZephyr/banger#3]
While case sensitivity can have usage, a vast majority of the time _(for me at least)_ it results in having to retype the query because CapsLock was enabled. An option to disable case-sensitivity by automatically converting capitalized characters in a query to lowercase would be great.

**Comment by WhistlingZephyr** [comment]
I realized that the case sensitivity was actually unintentional since DuckDuckGo and other engines seem to treat bangs case-insensitively. Thanks for submitting this issue. I've went ahead and added a quick fix for it. It's now case-insensitive by default and case-sensitivity is an opt-in config. (Live in v0.2.32)

![image](https://github.com/WhistlingZephyr/banger/assets/90854121/20db31c3-458c-4c59-b0fd-5a8676245c63)

I initially planned to wait till the next rewrite to add more features but given how I haven't been working on it that much and that it was a quick enough fix I decided to go ahead and implement it anyway.
